xtest <- read.table("./test/X_test.txt")
ytest <- read.table("./test/y_test.txt",col.names=c("activitylabel"))
subjecttest <- read.table("./test/subject_test.txt",col.names=c("subject"))
test <- cbind(ytest,subjecttest,xtest)
xtrain <- read.table("./train/X_train.txt")
ytrain <- read.table("./train/y_train.txt",col.names=c("activitylabel"))
subjecttrain <- read.table("./train/subject_train.txt",col.names=c("subject"))
train <- cbind(ytrain,subjecttrain,xtrain)
data <- rbind(test,train)
features <- read.table("./features.txt")
stdmean <- data[,grepl("std|mean\\()",features$V2)]
stdmean$activitylabel <- gsub("6","laying",stdmean$activitylabel)
stdmean$activitylabel <- gsub("5","standing",stdmean$activitylabel)
stdmean$activitylabel <- gsub("4","sitting",stdmean$activitylabel)
stdmean$activitylabel <- gsub("3","walking_downstairs",stdmean$activitylabel)
stdmean$activitylabel <- gsub("2","walking_upstairs",stdmean$activitylabel)
stdmean$activitylabel <- gsub("1","walking",stdmean$activitylabel)
grepfeatures <- grep("std|mean\\()",features$V2,value=TRUE)
names <- tolower(grepfeatures)
colnames(stdmean) <- c("activitylabel","subject",names)
library(reshape2)
melt <- melt(stdmean,id=c("activitylabel","subject"))
tidydata <- dcast(melt, subject + activitylabel ~ variable, fun.aggregate=mean)
write.table(tidydata,file="./tidydata.txt")